### ISSUE TITLE
Simplify name to mapbox-match

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-match.js#14]
Following on #1 #8  #12 #13 and discussions with @lxbarth @aaronlidman the suggestion is to call this just mapbox-match to keep it simple. 

- [x] Repo `mapbox-match.js`
- [x] API `L.mapbox.match`
- [x] JS `mapbox.match.js`
- [x] src `match.js`

@freenerd @tmcw @TheMarex  If no opposition, will make the change.

**Comment by freenerd** [comment]
I don't care either way, as long as it is consistent :smile:

**Comment by TheMarex** [comment]
Fine with me.

**Comment by freenerd** [comment]
The repository is now called `mapbox-match.js`.
