### ISSUE TITLE
Duplicate API response for separate requests

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-match.js#7]
Just investigated this with @aaronlidman but we are not sure whats going on. When loading the test page after>1 min, the matched geometries seem to be duplictes even though the requests geometries were different. After a reload this behaves normally.

Behavior observed even on a private session in Safari and Chrome so its not a cache issue. @freenerd any ideas?

![untitled](https://cloud.githubusercontent.com/assets/126868/8239738/c4fcbf3e-15cb-11e5-8524-519d8055b85a.gif)

Verifying that the request payloads were different but responses were the same.
![untitled1](https://cloud.githubusercontent.com/assets/126868/8221110/51e64f04-1528-11e5-8614-f551c51b391b.gif)

**Comment by freenerd** [comment]
Wow, super weird error. I did not see this before, can you get me some steps to reproduce?

**Comment by freenerd** [comment]
Could not reproduce. Re-open if we can find a test case.
